#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*                 linuxserver/cops                   *
*                                                    *
*      https://hub.docker.com/r/linuxserver/cops     *
*                                                    *
*     https://github.com/linuxserver/docker-cops     *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
